//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DataManage.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DATAMANAGE_DIALOG           102
#define IDR_HTML_PLAYERSOLDIER          103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_HEROPACK             129
#define IDD_DIALOG_RESOURCE             130
#define IDD_DIALOG_SOLDIER              131
#define IDD_DIALOG_WEAPON               132
#define IDD_DIALOG_HEROATTRI            133
#define IDD_DIALOG_RESOURCEVIEW         134
#define IDD_DIALOG1                     135
#define IDD_DLG_CONSORTIA               136
#define IDC_EDIT_DBGPORT                1000
#define IDC_IPADDRESS1                  1001
#define ID_BTN_CONNECT                  1002
#define IDC_BTN_HEROPACK                1003
#define IDC_BTN_RESOURCE                1004
#define IDC_BTN_SOLDIER                 1005
#define IDC_BTN_WEAPON                  1006
#define IDC_EDIT2                       1007
#define IDC_EDIT_CITYID                 1008
#define IDC_EDIT3                       1008
#define IDC_EDIT_FOOD                   1010
#define IDC_EDIT_WOOD                   1011
#define IDC_EDIT_SKIN                   1012
#define IDC_EDIT_IRON                   1013
#define IDC_EDIT_REDSTONE               1014
#define IDC_EDIT_YELLOWSTONE            1015
#define IDC_EDIT_GREENSTONE             1016
#define IDC_EDIT_BLACKIRON              1017
#define ID_ADDRESOURCE                  1018
#define IDC_EDIT_CONTENT                1018
#define IDC_STATIC_HINT                 1019
#define IDC_EDIT_TOTAL                  1019
#define IDC_EDIT_COUNT                  1022
#define ID_ADDITEM                      1023
#define IDC_EDIT_HUMAN                  1024
#define IDC_EDIT_MAPID                  1024
#define IDC_EDIT_MANNIKIN               1025
#define IDC_EDIT_FAIRY                  1026
#define IDC_EDIT_DANDIPRAT              1027
#define IDC_EDIT_HALFMAN                1028
#define IDC_EDIT_CATTLE                 1029
#define IDC_EDIT_BLACKFAIRY             1030
#define IDC_EDIT_DECPERSION             1031
#define ID_ADDSOLDIER                   1032
#define IDC_EDIT_PACKID                 1033
#define IDC_COMBO_MAP                   1035
#define IDC_BTN_REFRESH                 1036
#define IDC_BTN_ADDCONTENT              1037
#define IDC_EDIT_LEVEL                  1039
#define IDC_EDIT_STAMINA                1040
#define IDC_EDIT_POWER                  1041
#define IDC_EDIT_CELERITY               1042
#define IDC_EDIT_WIT                    1043
#define IDC_EDIT_TECHDOT                1044
#define ID_MODIFYHERO                   1045
#define IDC_EDIT_HEROID                 1046
#define IDC_BTN_HEROMANAGE              1046
#define IDC_COMBO1                      1047
#define IDC_BTN_RESUME                  1047
#define IDC_BUTTON_STATE                1048
#define IDC_EDIT_STATE                  1049
#define IDC_EDIT_MONEY                  1050
#define IDC_EDIT_SCIENCE                1051
#define IDC_ADDPLAYER                   1052
#define IDC_EDIT_CELERITY2              1053
#define IDC_BUTTON_HERO                 1054
#define IDC_EDIT_CELERITY3              1054
#define IDC_BUTTON_ADDCITY              1055
#define IDC_COMBO_POS                   1057
#define IDC_BUTTON_DATAVIEW             1058
#define IDC_BUTTON_DELETE               1059
#define IDC_BUTTON_INIT                 1060
#define IDC_STATIC_INFO                 1061
#define ID_BUTTON_QUERY                 1062
#define ID_BUTTON_ADD                   1063
#define IDC_EDIT_YSTONE                 1068
#define IDC_EDIT_RSTONE                 1069
#define IDC_EDIT_GSTONE                 1070
#define IDC_LIST_AMOUNT                 1072
#define IDC_EDIT_SUM                    1073
#define IDC_LIST_ITEM                   1074
#define IDC_EDIT_CURLEVEL               1076
#define IDC_EDIT_EXP                    1077
#define IDC_BUTTON_GETLEVEL             1078
#define IDC_BUTTON_DELCONS              1079
#define IDC_BUTTON_RESET                1081
#define IDC_EDIT_NAME                   1083
#define IDC_BUTTON1                     1084
#define ID_OK                           1085
#define IDC_BUTTON7                     1085
#define IDC_BUTTON2                     1087
#define IDC_EDIT_STARTID                1088
#define IDC_EDIT_ENDID                  1089
#define IDC_BUTTON_INITOFFICER          1090
#define IDC_COMBO_HEROJOB               1091
#define IDC_BUTTON3                     1092
#define IDC_EDIT1                       1094
#define IDC_COMBO3                      1095
#define IDC_COMBO4                      1096
#define IDC_COMBO5                      1097
#define IDC_COMBO2                      1098
#define IDC_BUTTON4                     1099
#define IDC_BUTTON5                     1100
#define IDC_BUTTON6                     1101
#define IDC_COMBO6                      1103
#define IDC_EDIT4                       1104
#define ID_QUERYCONSORTIA               1105
#define IDC_LIST1                       1106
#define IDC_BUTTON8                     1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
