#ifndef NET_BASE_PROTOCOL_H
#define NET_BASE_PROTOCOL_H
//#define  SOCKET_PACKAGE     1024 
#define  FIGHT_BASE_COMMAND        1000
#define  CHAT_BASE_COMMAND         2000
typedef struct  
{
	int iLen;
	int version;
	int checkCode;
	int cmdID;
	char buffer[1024];
}SEND_BLOCK;

typedef enum
{
	//REQ_ENTER_FIGHT_SYSTEM			= FIGHT_BASE_COMMAND +1,
	//RSP_ENTER_FIGHT_SYSTEM			= FIGHT_BASE_COMMAND +2,

	////////////////////////chat////////////////////////////////
	//REQ_ENTER_CHAT_SYSTEM			= CHAT_BASE_COMMAND +1,
	//REQ_ENTER_CHAT_ROOM				= CHAT_BASE_COMMAND +2,
	//RSP_ENTER_CHAT_ROOM				= CHAT_BASE_COMMAND +3,
	//REQ_SNED_CHAT_INFO				= CHAT_BASE_COMMAND +4,
	//RSP_SEND_CHAT_INFO				= CHAT_BASE_COMMAND +5,
	//REQ_EXIT_CHAT_SYSTEM			= CHAT_BASE_COMMAND +6,
	//REQ_EXIT_CHAT_ROOM				= CHAT_BASE_COMMAND +7,
	//REQ_INVITE_OTHER_ENTER_CHAT_ROOM = CHAT_BASE_COMMAND +8,
	//RSP_INVITE_OTHER_ENTER_CHAT_ROOM = CHAT_BASE_COMMAND +9,
	//RSP_OTHER_ENTER_CHAT_ROOM		= CHAT_BASE_COMMAND +10,
}COMMAND_ID;
#endif