// @brief 伤害系统命名空间定义头文件
// @author 张文龙

#ifndef COMPUTINGHURT_NAMESPACEDEF_H_
#define COMPUTINGHURT_NAMESPACEDEF_H_

#define COMPUTINGHURT_NAMESPACE_BEGIN namespace computinghurt {
#define COMPUTINGHURT_NAMESPACE_END }

#define STATISTICSSYSTEM_NAMESPACE_BEGIN namespace statisticssystem {
#define STATISTICSSYSTEM_NAMESPACE_END }

#endif // COMPUTINGHURT_NAMESPACEDEF_H_